import { ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';

export const C={bg:'#F8F7F2',ink:'#111111',muted:'#6C6962',line:'#E2DFD7',card:'#FFFFFF',accent:'#4F46E5',soft:'#EEEDFF'};
export function Shell({step,title,subtitle,children,next,nextLabel='Continue'}:{step:string;title:string;subtitle?:string;children:ReactNode;next?:()=>void;nextLabel?:string}){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.top}><Text style={s.kicker}>{step}</Text><Text style={s.brand}>SPARKHUB</Text></View><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.sub}>{subtitle}</Text>}{children}{next&&<Pressable onPress={next} style={s.primary}><Text style={s.primaryText}>{nextLabel}</Text><Text style={s.arrow}>→</Text></Pressable>}</ScrollView></SafeAreaView>}
export function Field({label,value,onChangeText,placeholder,multiline=false,keyboardType}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#9A978F" keyboardType={keyboardType} multiline={multiline} textAlignVertical={multiline?'top':'center'} style={[s.input,multiline&&s.area]}/></View>}
export function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,selected&&s.choiceOn]}><Text style={[s.choiceText,selected&&s.choiceTextOn]}>{label}</Text>{selected&&<Text style={s.check}>✓</Text>}</Pressable>}
export function Back(){return <Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹ Back</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:24,paddingBottom:48},top:{flexDirection:'row',justifyContent:'space-between',marginBottom:22},kicker:{color:C.accent,fontWeight:'800',fontSize:12,letterSpacing:1.4},brand:{color:'#8E8B84',fontWeight:'800',fontSize:11,letterSpacing:1.2},title:{color:C.ink,fontSize:31,lineHeight:36,fontWeight:'800',letterSpacing:-.7},sub:{color:C.muted,fontSize:15,lineHeight:23,marginTop:10,marginBottom:26},field:{marginBottom:18},label:{color:'#26251F',fontSize:13,fontWeight:'800',marginBottom:8},input:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:15,paddingHorizontal:15,minHeight:52,color:'#171714',fontSize:15},area:{minHeight:112,paddingTop:14},choice:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:15,padding:16,marginBottom:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},choiceOn:{borderColor:C.accent,backgroundColor:C.soft},choiceText:{color:'#34322D',fontSize:14,fontWeight:'700'},choiceTextOn:{color:'#26215E'},check:{color:C.accent,fontWeight:'900'},primary:{marginTop:12,backgroundColor:C.accent,borderRadius:17,paddingVertical:17,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},primaryText:{color:'#FFF',fontSize:16,fontWeight:'800'},arrow:{color:'#FFF',fontSize:20,fontWeight:'700'},back:{marginBottom:18},backText:{color:C.muted,fontSize:14,fontWeight:'700'}});
