/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assessment`; params?: Router.UnknownInputParams; } | { pathname: `/blueprint`; params?: Router.UnknownInputParams; } | { pathname: `/discovery`; params?: Router.UnknownInputParams; } | { pathname: `/dossier`; params?: Router.UnknownInputParams; } | { pathname: `/education`; params?: Router.UnknownInputParams; } | { pathname: `/full-report`; params?: Router.UnknownInputParams; } | { pathname: `/idea`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/network`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/professional`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/project`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/submitted`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/assessment`; params?: Router.UnknownOutputParams; } | { pathname: `/blueprint`; params?: Router.UnknownOutputParams; } | { pathname: `/discovery`; params?: Router.UnknownOutputParams; } | { pathname: `/dossier`; params?: Router.UnknownOutputParams; } | { pathname: `/education`; params?: Router.UnknownOutputParams; } | { pathname: `/full-report`; params?: Router.UnknownOutputParams; } | { pathname: `/idea`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/network`; params?: Router.UnknownOutputParams; } | { pathname: `/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/professional`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/project`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/submitted`; params?: Router.UnknownOutputParams; } | { pathname: `/team`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/assessment${`?${string}` | `#${string}` | ''}` | `/blueprint${`?${string}` | `#${string}` | ''}` | `/discovery${`?${string}` | `#${string}` | ''}` | `/dossier${`?${string}` | `#${string}` | ''}` | `/education${`?${string}` | `#${string}` | ''}` | `/full-report${`?${string}` | `#${string}` | ''}` | `/idea${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/network${`?${string}` | `#${string}` | ''}` | `/paywall${`?${string}` | `#${string}` | ''}` | `/professional${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/project${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/submitted${`?${string}` | `#${string}` | ''}` | `/team${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assessment`; params?: Router.UnknownInputParams; } | { pathname: `/blueprint`; params?: Router.UnknownInputParams; } | { pathname: `/discovery`; params?: Router.UnknownInputParams; } | { pathname: `/dossier`; params?: Router.UnknownInputParams; } | { pathname: `/education`; params?: Router.UnknownInputParams; } | { pathname: `/full-report`; params?: Router.UnknownInputParams; } | { pathname: `/idea`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/network`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/professional`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/project`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/submitted`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
